-- Generated by WOW/stats-pro-meta/tools/update-archon-targets.ps1
-- Do not edit by hand.
StatsProArchonTargets = {
  schemaVersion = 2,
  source = "archon",
  snapshots = {
    ["mythicPlus"] = {
      label = "M+ High Keys",
      title = "M+ Target",
      activity = "mythic-plus",
      bracket = "high-keys",
      dungeon = "all-dungeons",
      window = "this-week",
      capturedAt = "2026-05-24",
      specs = {
        ["DEATHKNIGHT"] = {
          ["blood"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/blood/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 618,
              haste = 471,
              mastery = 731,
              versatility = 551,
            },
            order = { "mastery", "crit", "versatility", "haste" },
          },
          ["frost"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/frost/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 932,
              haste = 419,
              mastery = 1071,
              versatility = 88,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["unholy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/unholy/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1027,
              haste = 368,
              mastery = 1094,
              versatility = 55,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["DEMONHUNTER"] = {
          ["devourer"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/devourer/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 267,
              haste = 1080,
              mastery = 1189,
              versatility = 56,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["havoc"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/havoc/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1202,
              haste = 281,
              mastery = 941,
              versatility = 67,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["vengeance"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/vengeance/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 614,
              haste = 1100,
              mastery = 336,
              versatility = 331,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
        ["DRUID"] = {
          ["balance"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/balance/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 734,
              haste = 783,
              mastery = 908,
              versatility = 98,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["feral"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/feral/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 520,
              haste = 756,
              mastery = 1081,
              versatility = 116,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["guardian"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/guardian/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 363,
              haste = 1147,
              mastery = 423,
              versatility = 540,
            },
            order = { "haste", "versatility", "mastery", "crit" },
          },
          ["restoration"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/restoration/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 98,
              haste = 1141,
              mastery = 1058,
              versatility = 218,
            },
            order = { "haste", "mastery", "versatility", "crit" },
          },
        },
        ["EVOKER"] = {
          ["augmentation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/augmentation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1298,
              haste = 871,
              mastery = 265,
              versatility = 73,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["devastation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/devastation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1179,
              haste = 754,
              mastery = 446,
              versatility = 100,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["preservation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/preservation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 555,
              haste = 795,
              mastery = 970,
              versatility = 167,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
        },
        ["HUNTER"] = {
          ["beast-mastery"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/beast-mastery/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1079,
              haste = 409,
              mastery = 978,
              versatility = 88,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["marksmanship"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/marksmanship/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1309,
              haste = 408,
              mastery = 685,
              versatility = 128,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["survival"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/survival/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 802,
              haste = 559,
              mastery = 1156,
              versatility = 87,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["MAGE"] = {
          ["arcane"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/arcane/mage/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 721,
              haste = 595,
              mastery = 872,
              versatility = 264,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["fire"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/fire/mage/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 105,
              haste = 1117,
              mastery = 998,
              versatility = 166,
            },
            order = { "haste", "mastery", "versatility", "crit" },
          },
          ["frost"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/frost/mage/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1053,
              haste = 561,
              mastery = 868,
              versatility = 90,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
        },
        ["MONK"] = {
          ["brewmaster"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/brewmaster/monk/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1126,
              haste = 252,
              mastery = 369,
              versatility = 774,
            },
            order = { "crit", "versatility", "mastery", "haste" },
          },
          ["mistweaver"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/mistweaver/monk/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 823,
              haste = 1140,
              mastery = 170,
              versatility = 377,
            },
            order = { "haste", "crit", "versatility", "mastery" },
          },
          ["windwalker"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/windwalker/monk/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 800,
              haste = 899,
              mastery = 688,
              versatility = 135,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
        ["PALADIN"] = {
          ["holy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/holy/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 381,
              haste = 930,
              mastery = 817,
              versatility = 294,
            },
            order = { "haste", "mastery", "crit", "versatility" },
          },
          ["protection"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/protection/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 830,
              haste = 1021,
              mastery = 334,
              versatility = 236,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["retribution"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/retribution/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 900,
              haste = 603,
              mastery = 927,
              versatility = 75,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["PRIEST"] = {
          ["discipline"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/discipline/priest/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 913,
              haste = 901,
              mastery = 575,
              versatility = 121,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["holy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/holy/priest/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 923,
              haste = 768,
              mastery = 327,
              versatility = 323,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["shadow"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/shadow/priest/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 543,
              haste = 1012,
              mastery = 899,
              versatility = 84,
            },
            order = { "haste", "mastery", "crit", "versatility" },
          },
        },
        ["ROGUE"] = {
          ["assassination"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/assassination/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1216,
              haste = 649,
              mastery = 514,
              versatility = 92,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["outlaw"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/outlaw/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1189,
              haste = 893,
              mastery = 298,
              versatility = 155,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["subtlety"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/subtlety/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 698,
              haste = 590,
              mastery = 1125,
              versatility = 80,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["SHAMAN"] = {
          ["elemental"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/elemental/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 815,
              haste = 464,
              mastery = 1126,
              versatility = 82,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["enhancement"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/enhancement/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 317,
              haste = 975,
              mastery = 1107,
              versatility = 74,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["restoration"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/restoration/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1079,
              haste = 496,
              mastery = 277,
              versatility = 576,
            },
            order = { "crit", "versatility", "haste", "mastery" },
          },
        },
        ["WARLOCK"] = {
          ["affliction"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/affliction/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 982,
              haste = 894,
              mastery = 504,
              versatility = 120,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["demonology"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/demonology/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1167,
              haste = 784,
              mastery = 482,
              versatility = 90,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["destruction"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/destruction/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 938,
              haste = 882,
              mastery = 563,
              versatility = 111,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
        },
        ["WARRIOR"] = {
          ["arms"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/arms/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1152,
              haste = 966,
              mastery = 346,
              versatility = 59,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["fury"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/fury/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 516,
              haste = 1064,
              mastery = 1036,
              versatility = 83,
            },
            order = { "haste", "mastery", "crit", "versatility" },
          },
          ["protection"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/protection/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 576,
              haste = 1131,
              mastery = 379,
              versatility = 240,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
      },
    },
    ["raid"] = {
      label = "Raid Mythic All Bosses",
      title = "Raid Target",
      activity = "raid",
      difficulty = "mythic",
      boss = "all-bosses",
      window = "last-14-days",
      capturedAt = "2026-05-24",
      specs = {
        ["DEATHKNIGHT"] = {
          ["blood"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/blood/death-knight/raid/overview/mythic/all-bosses",
            targets = {
              crit = 784,
              haste = 829,
              mastery = 609,
              versatility = 238,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["frost"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/frost/death-knight/raid/overview/mythic/all-bosses",
            targets = {
              crit = 972,
              haste = 396,
              mastery = 1102,
              versatility = 72,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["unholy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/unholy/death-knight/raid/overview/mythic/all-bosses",
            targets = {
              crit = 982,
              haste = 399,
              mastery = 1084,
              versatility = 68,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["DEMONHUNTER"] = {
          ["devourer"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/devourer/demon-hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 283,
              haste = 1024,
              mastery = 1199,
              versatility = 66,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["havoc"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/havoc/demon-hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1165,
              haste = 334,
              mastery = 921,
              versatility = 82,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["vengeance"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/vengeance/demon-hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 671,
              haste = 1065,
              mastery = 435,
              versatility = 265,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
        ["DRUID"] = {
          ["balance"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/balance/druid/raid/overview/mythic/all-bosses",
            targets = {
              crit = 730,
              haste = 742,
              mastery = 978,
              versatility = 123,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["feral"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/feral/druid/raid/overview/mythic/all-bosses",
            targets = {
              crit = 560,
              haste = 788,
              mastery = 1043,
              versatility = 151,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["guardian"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/guardian/druid/raid/overview/mythic/all-bosses",
            targets = {
              crit = 402,
              haste = 1093,
              mastery = 460,
              versatility = 460,
            },
            order = { "haste", "versatility", "mastery", "crit" },
          },
          ["restoration"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/restoration/druid/raid/overview/mythic/all-bosses",
            targets = {
              crit = 154,
              haste = 1186,
              mastery = 1029,
              versatility = 181,
            },
            order = { "haste", "mastery", "versatility", "crit" },
          },
        },
        ["EVOKER"] = {
          ["augmentation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/augmentation/evoker/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1284,
              haste = 819,
              mastery = 288,
              versatility = 89,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["devastation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/devastation/evoker/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1245,
              haste = 746,
              mastery = 418,
              versatility = 89,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["preservation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/preservation/evoker/raid/overview/mythic/all-bosses",
            targets = {
              crit = 810,
              haste = 516,
              mastery = 1176,
              versatility = 116,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["HUNTER"] = {
          ["beast-mastery"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/beast-mastery/hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 997,
              haste = 497,
              mastery = 958,
              versatility = 85,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["marksmanship"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/marksmanship/hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1309,
              haste = 417,
              mastery = 755,
              versatility = 105,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["survival"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/survival/hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 812,
              haste = 572,
              mastery = 1170,
              versatility = 87,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["MAGE"] = {
          ["arcane"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/arcane/mage/raid/overview/mythic/all-bosses",
            targets = {
              crit = 761,
              haste = 635,
              mastery = 864,
              versatility = 250,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["fire"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/fire/mage/raid/overview/mythic/all-bosses",
            targets = {
              crit = 159,
              haste = 1182,
              mastery = 933,
              versatility = 174,
            },
            order = { "haste", "mastery", "versatility", "crit" },
          },
          ["frost"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/frost/mage/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1052,
              haste = 566,
              mastery = 848,
              versatility = 89,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
        },
        ["MONK"] = {
          ["brewmaster"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/brewmaster/monk/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1161,
              haste = 296,
              mastery = 411,
              versatility = 660,
            },
            order = { "crit", "versatility", "mastery", "haste" },
          },
          ["mistweaver"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/mistweaver/monk/raid/overview/mythic/all-bosses",
            targets = {
              crit = 919,
              haste = 1189,
              mastery = 202,
              versatility = 183,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["windwalker"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/windwalker/monk/raid/overview/mythic/all-bosses",
            targets = {
              crit = 826,
              haste = 903,
              mastery = 661,
              versatility = 152,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
        ["PALADIN"] = {
          ["holy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/holy/paladin/raid/overview/mythic/all-bosses",
            targets = {
              crit = 476,
              haste = 845,
              mastery = 1076,
              versatility = 144,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["protection"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/protection/paladin/raid/overview/mythic/all-bosses",
            targets = {
              crit = 730,
              haste = 1032,
              mastery = 437,
              versatility = 248,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["retribution"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/retribution/paladin/raid/overview/mythic/all-bosses",
            targets = {
              crit = 860,
              haste = 620,
              mastery = 963,
              versatility = 77,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["PRIEST"] = {
          ["discipline"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/discipline/priest/raid/overview/mythic/all-bosses",
            targets = {
              crit = 870,
              haste = 1026,
              mastery = 508,
              versatility = 106,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["holy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/holy/priest/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1083,
              haste = 550,
              mastery = 632,
              versatility = 205,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["shadow"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/shadow/priest/raid/overview/mythic/all-bosses",
            targets = {
              crit = 522,
              haste = 984,
              mastery = 971,
              versatility = 79,
            },
            order = { "haste", "mastery", "crit", "versatility" },
          },
        },
        ["ROGUE"] = {
          ["assassination"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/assassination/rogue/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1187,
              haste = 658,
              mastery = 518,
              versatility = 106,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["outlaw"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/outlaw/rogue/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1192,
              haste = 867,
              mastery = 286,
              versatility = 173,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["subtlety"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/subtlety/rogue/raid/overview/mythic/all-bosses",
            targets = {
              crit = 740,
              haste = 676,
              mastery = 975,
              versatility = 93,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["SHAMAN"] = {
          ["elemental"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/elemental/shaman/raid/overview/mythic/all-bosses",
            targets = {
              crit = 840,
              haste = 480,
              mastery = 1084,
              versatility = 93,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["enhancement"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/enhancement/shaman/raid/overview/mythic/all-bosses",
            targets = {
              crit = 312,
              haste = 950,
              mastery = 1138,
              versatility = 83,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["restoration"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/restoration/shaman/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1191,
              haste = 460,
              mastery = 340,
              versatility = 422,
            },
            order = { "crit", "haste", "versatility", "mastery" },
          },
        },
        ["WARLOCK"] = {
          ["affliction"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/affliction/warlock/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1034,
              haste = 879,
              mastery = 514,
              versatility = 108,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["demonology"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/demonology/warlock/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1138,
              haste = 807,
              mastery = 483,
              versatility = 95,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["destruction"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/destruction/warlock/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1019,
              haste = 836,
              mastery = 562,
              versatility = 91,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
        },
        ["WARRIOR"] = {
          ["arms"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/arms/warrior/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1119,
              haste = 962,
              mastery = 344,
              versatility = 71,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["fury"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/fury/warrior/raid/overview/mythic/all-bosses",
            targets = {
              crit = 482,
              haste = 1066,
              mastery = 1055,
              versatility = 88,
            },
            order = { "haste", "mastery", "crit", "versatility" },
          },
          ["protection"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/protection/warrior/raid/overview/mythic/all-bosses",
            targets = {
              crit = 674,
              haste = 1121,
              mastery = 456,
              versatility = 207,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
      },
    },
  },
}
