-- Generated by WOW/stats-pro-meta/tools/update-archon-targets.ps1
-- Do not edit by hand.
StatsProArchonTargets = {
  schemaVersion = 1,
  source = "archon",
  activity = "mythic-plus",
  bracket = "high-keys",
  dungeon = "all-dungeons",
  window = "this-week",
  capturedAt = "2026-05-15",
  specs = {
    ["DEATHKNIGHT"] = {
      ["blood"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/blood/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 653,
          haste = 466,
          mastery = 683,
          versatility = 572,
        },
        order = { "mastery", "crit", "versatility", "haste" },
      },
      ["frost"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/frost/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 921,
          haste = 419,
          mastery = 1043,
          versatility = 92,
        },
        order = { "mastery", "crit", "haste", "versatility" },
      },
      ["unholy"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/unholy/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 989,
          haste = 387,
          mastery = 1062,
          versatility = 56,
        },
        order = { "mastery", "crit", "haste", "versatility" },
      },
    },
    ["DEMONHUNTER"] = {
      ["devourer"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/devourer/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 259,
          haste = 1036,
          mastery = 1187,
          versatility = 58,
        },
        order = { "mastery", "haste", "crit", "versatility" },
      },
      ["havoc"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/havoc/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1185,
          haste = 290,
          mastery = 906,
          versatility = 66,
        },
        order = { "crit", "mastery", "haste", "versatility" },
      },
      ["vengeance"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/vengeance/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 593,
          haste = 1086,
          mastery = 318,
          versatility = 373,
        },
        order = { "haste", "crit", "versatility", "mastery" },
      },
    },
    ["DRUID"] = {
      ["balance"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/balance/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 696,
          haste = 762,
          mastery = 910,
          versatility = 106,
        },
        order = { "mastery", "haste", "crit", "versatility" },
      },
      ["feral"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/feral/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 513,
          haste = 723,
          mastery = 1087,
          versatility = 121,
        },
        order = { "mastery", "haste", "crit", "versatility" },
      },
      ["guardian"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/guardian/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 381,
          haste = 1052,
          mastery = 496,
          versatility = 453,
        },
        order = { "haste", "mastery", "versatility", "crit" },
      },
      ["restoration"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/restoration/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 90,
          haste = 1133,
          mastery = 1059,
          versatility = 224,
        },
        order = { "haste", "mastery", "versatility", "crit" },
      },
    },
    ["EVOKER"] = {
      ["augmentation"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/augmentation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1280,
          haste = 837,
          mastery = 264,
          versatility = 76,
        },
        order = { "crit", "haste", "mastery", "versatility" },
      },
      ["devastation"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/devastation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1177,
          haste = 730,
          mastery = 444,
          versatility = 87,
        },
        order = { "crit", "haste", "mastery", "versatility" },
      },
      ["preservation"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/preservation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 545,
          haste = 783,
          mastery = 963,
          versatility = 162,
        },
        order = { "mastery", "haste", "crit", "versatility" },
      },
    },
    ["HUNTER"] = {
      ["beast-mastery"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/beast-mastery/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1039,
          haste = 409,
          mastery = 976,
          versatility = 84,
        },
        order = { "crit", "mastery", "haste", "versatility" },
      },
      ["marksmanship"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/marksmanship/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1284,
          haste = 411,
          mastery = 624,
          versatility = 129,
        },
        order = { "crit", "mastery", "haste", "versatility" },
      },
      ["survival"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/survival/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 780,
          haste = 551,
          mastery = 1142,
          versatility = 86,
        },
        order = { "mastery", "crit", "haste", "versatility" },
      },
    },
    ["MAGE"] = {
      ["arcane"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/arcane/mage/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 730,
          haste = 593,
          mastery = 868,
          versatility = 265,
        },
        order = { "mastery", "crit", "haste", "versatility" },
      },
      ["fire"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/fire/mage/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 117,
          haste = 1118,
          mastery = 919,
          versatility = 175,
        },
        order = { "haste", "mastery", "versatility", "crit" },
      },
      ["frost"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/frost/mage/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1031,
          haste = 557,
          mastery = 851,
          versatility = 95,
        },
        order = { "crit", "mastery", "haste", "versatility" },
      },
    },
    ["MONK"] = {
      ["brewmaster"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/brewmaster/monk/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1125,
          haste = 255,
          mastery = 350,
          versatility = 770,
        },
        order = { "crit", "versatility", "mastery", "haste" },
      },
      ["mistweaver"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/mistweaver/monk/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 779,
          haste = 1148,
          mastery = 167,
          versatility = 311,
        },
        order = { "haste", "crit", "versatility", "mastery" },
      },
      ["windwalker"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/windwalker/monk/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 789,
          haste = 911,
          mastery = 670,
          versatility = 128,
        },
        order = { "haste", "crit", "mastery", "versatility" },
      },
    },
    ["PALADIN"] = {
      ["holy"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/holy/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 371,
          haste = 927,
          mastery = 781,
          versatility = 298,
        },
        order = { "haste", "mastery", "crit", "versatility" },
      },
      ["protection"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/protection/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 774,
          haste = 1013,
          mastery = 321,
          versatility = 261,
        },
        order = { "haste", "crit", "mastery", "versatility" },
      },
      ["retribution"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/retribution/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 865,
          haste = 611,
          mastery = 905,
          versatility = 74,
        },
        order = { "mastery", "crit", "haste", "versatility" },
      },
    },
    ["PRIEST"] = {
      ["discipline"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/discipline/priest/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 895,
          haste = 911,
          mastery = 547,
          versatility = 132,
        },
        order = { "haste", "crit", "mastery", "versatility" },
      },
      ["holy"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/holy/priest/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 949,
          haste = 759,
          mastery = 308,
          versatility = 316,
        },
        order = { "crit", "haste", "versatility", "mastery" },
      },
      ["shadow"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/shadow/priest/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 520,
          haste = 980,
          mastery = 915,
          versatility = 82,
        },
        order = { "haste", "mastery", "crit", "versatility" },
      },
    },
    ["ROGUE"] = {
      ["assassination"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/assassination/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1195,
          haste = 634,
          mastery = 507,
          versatility = 85,
        },
        order = { "crit", "haste", "mastery", "versatility" },
      },
      ["outlaw"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/outlaw/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1143,
          haste = 885,
          mastery = 292,
          versatility = 155,
        },
        order = { "crit", "haste", "mastery", "versatility" },
      },
      ["subtlety"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/subtlety/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 718,
          haste = 564,
          mastery = 1089,
          versatility = 80,
        },
        order = { "mastery", "crit", "haste", "versatility" },
      },
    },
    ["SHAMAN"] = {
      ["elemental"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/elemental/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 784,
          haste = 475,
          mastery = 1108,
          versatility = 82,
        },
        order = { "mastery", "crit", "haste", "versatility" },
      },
      ["enhancement"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/enhancement/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 276,
          haste = 942,
          mastery = 1165,
          versatility = 73,
        },
        order = { "mastery", "haste", "crit", "versatility" },
      },
      ["restoration"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/restoration/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1075,
          haste = 490,
          mastery = 264,
          versatility = 539,
        },
        order = { "crit", "versatility", "haste", "mastery" },
      },
    },
    ["WARLOCK"] = {
      ["affliction"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/affliction/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 965,
          haste = 894,
          mastery = 475,
          versatility = 113,
        },
        order = { "crit", "haste", "mastery", "versatility" },
      },
      ["demonology"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/demonology/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1163,
          haste = 780,
          mastery = 442,
          versatility = 90,
        },
        order = { "crit", "haste", "mastery", "versatility" },
      },
      ["destruction"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/destruction/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 912,
          haste = 877,
          mastery = 517,
          versatility = 110,
        },
        order = { "crit", "haste", "mastery", "versatility" },
      },
    },
    ["WARRIOR"] = {
      ["arms"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/arms/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 1124,
          haste = 936,
          mastery = 343,
          versatility = 58,
        },
        order = { "crit", "haste", "mastery", "versatility" },
      },
      ["fury"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/fury/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 500,
          haste = 1049,
          mastery = 1025,
          versatility = 87,
        },
        order = { "haste", "mastery", "crit", "versatility" },
      },
      ["protection"] = {
        sourceUrl = "https://www.archon.gg/wow/builds/protection/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week",
        targets = {
          crit = 570,
          haste = 1116,
          mastery = 366,
          versatility = 241,
        },
        order = { "haste", "crit", "mastery", "versatility" },
      },
    },
  },
}
