-- Generated by WOW/stats-pro-meta/tools/update-archon-targets.ps1
-- Do not edit by hand.
StatsProArchonTargets = {
  schemaVersion = 2,
  source = "archon",
  snapshots = {
    ["mythicPlus"] = {
      label = "M+ High Keys",
      title = "M+ Target",
      activity = "mythic-plus",
      bracket = "high-keys",
      dungeon = "all-dungeons",
      window = "this-week",
      capturedAt = "2026-05-17",
      specs = {
        ["DEATHKNIGHT"] = {
          ["blood"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/blood/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 653,
              haste = 466,
              mastery = 683,
              versatility = 572,
            },
            order = { "mastery", "crit", "versatility", "haste" },
          },
          ["frost"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/frost/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 921,
              haste = 419,
              mastery = 1043,
              versatility = 92,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["unholy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/unholy/death-knight/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 989,
              haste = 387,
              mastery = 1062,
              versatility = 56,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["DEMONHUNTER"] = {
          ["devourer"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/devourer/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 259,
              haste = 1036,
              mastery = 1187,
              versatility = 58,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["havoc"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/havoc/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1185,
              haste = 290,
              mastery = 906,
              versatility = 66,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["vengeance"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/vengeance/demon-hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 593,
              haste = 1086,
              mastery = 318,
              versatility = 373,
            },
            order = { "haste", "crit", "versatility", "mastery" },
          },
        },
        ["DRUID"] = {
          ["balance"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/balance/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 696,
              haste = 762,
              mastery = 910,
              versatility = 106,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["feral"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/feral/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 513,
              haste = 723,
              mastery = 1087,
              versatility = 121,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["guardian"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/guardian/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 381,
              haste = 1052,
              mastery = 496,
              versatility = 453,
            },
            order = { "haste", "mastery", "versatility", "crit" },
          },
          ["restoration"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/restoration/druid/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 90,
              haste = 1133,
              mastery = 1059,
              versatility = 224,
            },
            order = { "haste", "mastery", "versatility", "crit" },
          },
        },
        ["EVOKER"] = {
          ["augmentation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/augmentation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1280,
              haste = 837,
              mastery = 264,
              versatility = 76,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["devastation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/devastation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1177,
              haste = 730,
              mastery = 444,
              versatility = 87,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["preservation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/preservation/evoker/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 545,
              haste = 783,
              mastery = 963,
              versatility = 162,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
        },
        ["HUNTER"] = {
          ["beast-mastery"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/beast-mastery/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1039,
              haste = 409,
              mastery = 976,
              versatility = 84,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["marksmanship"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/marksmanship/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1284,
              haste = 411,
              mastery = 624,
              versatility = 129,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["survival"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/survival/hunter/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 780,
              haste = 551,
              mastery = 1142,
              versatility = 86,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["MAGE"] = {
          ["arcane"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/arcane/mage/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 730,
              haste = 593,
              mastery = 868,
              versatility = 265,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["fire"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/fire/mage/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 117,
              haste = 1118,
              mastery = 919,
              versatility = 175,
            },
            order = { "haste", "mastery", "versatility", "crit" },
          },
          ["frost"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/frost/mage/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1031,
              haste = 557,
              mastery = 851,
              versatility = 95,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
        },
        ["MONK"] = {
          ["brewmaster"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/brewmaster/monk/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1125,
              haste = 255,
              mastery = 350,
              versatility = 770,
            },
            order = { "crit", "versatility", "mastery", "haste" },
          },
          ["mistweaver"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/mistweaver/monk/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 779,
              haste = 1148,
              mastery = 167,
              versatility = 311,
            },
            order = { "haste", "crit", "versatility", "mastery" },
          },
          ["windwalker"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/windwalker/monk/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 789,
              haste = 911,
              mastery = 670,
              versatility = 128,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
        ["PALADIN"] = {
          ["holy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/holy/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 371,
              haste = 927,
              mastery = 781,
              versatility = 298,
            },
            order = { "haste", "mastery", "crit", "versatility" },
          },
          ["protection"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/protection/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 774,
              haste = 1013,
              mastery = 321,
              versatility = 261,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["retribution"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/retribution/paladin/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 865,
              haste = 611,
              mastery = 905,
              versatility = 74,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["PRIEST"] = {
          ["discipline"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/discipline/priest/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 895,
              haste = 911,
              mastery = 547,
              versatility = 132,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["holy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/holy/priest/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 949,
              haste = 759,
              mastery = 308,
              versatility = 316,
            },
            order = { "crit", "haste", "versatility", "mastery" },
          },
          ["shadow"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/shadow/priest/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 520,
              haste = 980,
              mastery = 915,
              versatility = 82,
            },
            order = { "haste", "mastery", "crit", "versatility" },
          },
        },
        ["ROGUE"] = {
          ["assassination"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/assassination/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1195,
              haste = 634,
              mastery = 507,
              versatility = 85,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["outlaw"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/outlaw/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1143,
              haste = 885,
              mastery = 292,
              versatility = 155,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["subtlety"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/subtlety/rogue/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 718,
              haste = 564,
              mastery = 1089,
              versatility = 80,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["SHAMAN"] = {
          ["elemental"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/elemental/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 784,
              haste = 475,
              mastery = 1108,
              versatility = 82,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["enhancement"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/enhancement/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 276,
              haste = 942,
              mastery = 1165,
              versatility = 73,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["restoration"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/restoration/shaman/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1075,
              haste = 490,
              mastery = 264,
              versatility = 539,
            },
            order = { "crit", "versatility", "haste", "mastery" },
          },
        },
        ["WARLOCK"] = {
          ["affliction"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/affliction/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 965,
              haste = 894,
              mastery = 475,
              versatility = 113,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["demonology"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/demonology/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1163,
              haste = 780,
              mastery = 442,
              versatility = 90,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["destruction"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/destruction/warlock/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 912,
              haste = 877,
              mastery = 517,
              versatility = 110,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
        },
        ["WARRIOR"] = {
          ["arms"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/arms/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 1124,
              haste = 936,
              mastery = 343,
              versatility = 58,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["fury"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/fury/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 500,
              haste = 1049,
              mastery = 1025,
              versatility = 87,
            },
            order = { "haste", "mastery", "crit", "versatility" },
          },
          ["protection"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/protection/warrior/mythic-plus/overview/high-keys/all-dungeons/this-week",
            targets = {
              crit = 570,
              haste = 1116,
              mastery = 366,
              versatility = 241,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
      },
    },
    ["raid"] = {
      label = "Raid Mythic All Bosses",
      title = "Raid Target",
      activity = "raid",
      difficulty = "mythic",
      boss = "all-bosses",
      window = "last-14-days",
      capturedAt = "2026-05-17",
      specs = {
        ["DEATHKNIGHT"] = {
          ["blood"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/blood/death-knight/raid/overview/mythic/all-bosses",
            targets = {
              crit = 776,
              haste = 828,
              mastery = 598,
              versatility = 246,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["frost"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/frost/death-knight/raid/overview/mythic/all-bosses",
            targets = {
              crit = 952,
              haste = 403,
              mastery = 1085,
              versatility = 77,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["unholy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/unholy/death-knight/raid/overview/mythic/all-bosses",
            targets = {
              crit = 954,
              haste = 408,
              mastery = 1060,
              versatility = 69,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["DEMONHUNTER"] = {
          ["devourer"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/devourer/demon-hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 283,
              haste = 995,
              mastery = 1192,
              versatility = 69,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["havoc"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/havoc/demon-hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1138,
              haste = 336,
              mastery = 892,
              versatility = 83,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["vengeance"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/vengeance/demon-hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 669,
              haste = 1044,
              mastery = 426,
              versatility = 270,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
        ["DRUID"] = {
          ["balance"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/balance/druid/raid/overview/mythic/all-bosses",
            targets = {
              crit = 692,
              haste = 721,
              mastery = 996,
              versatility = 116,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["feral"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/feral/druid/raid/overview/mythic/all-bosses",
            targets = {
              crit = 560,
              haste = 769,
              mastery = 1050,
              versatility = 128,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["guardian"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/guardian/druid/raid/overview/mythic/all-bosses",
            targets = {
              crit = 417,
              haste = 1050,
              mastery = 469,
              versatility = 415,
            },
            order = { "haste", "mastery", "crit", "versatility" },
          },
          ["restoration"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/restoration/druid/raid/overview/mythic/all-bosses",
            targets = {
              crit = 151,
              haste = 1174,
              mastery = 995,
              versatility = 180,
            },
            order = { "haste", "mastery", "versatility", "crit" },
          },
        },
        ["EVOKER"] = {
          ["augmentation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/augmentation/evoker/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1269,
              haste = 795,
              mastery = 289,
              versatility = 90,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["devastation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/devastation/evoker/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1230,
              haste = 715,
              mastery = 417,
              versatility = 93,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["preservation"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/preservation/evoker/raid/overview/mythic/all-bosses",
            targets = {
              crit = 764,
              haste = 519,
              mastery = 1136,
              versatility = 117,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["HUNTER"] = {
          ["beast-mastery"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/beast-mastery/hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 986,
              haste = 494,
              mastery = 963,
              versatility = 85,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["marksmanship"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/marksmanship/hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1300,
              haste = 409,
              mastery = 723,
              versatility = 107,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["survival"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/survival/hunter/raid/overview/mythic/all-bosses",
            targets = {
              crit = 787,
              haste = 563,
              mastery = 1155,
              versatility = 88,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["MAGE"] = {
          ["arcane"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/arcane/mage/raid/overview/mythic/all-bosses",
            targets = {
              crit = 739,
              haste = 640,
              mastery = 857,
              versatility = 252,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["fire"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/fire/mage/raid/overview/mythic/all-bosses",
            targets = {
              crit = 154,
              haste = 1173,
              mastery = 917,
              versatility = 164,
            },
            order = { "haste", "mastery", "versatility", "crit" },
          },
          ["frost"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/frost/mage/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1036,
              haste = 562,
              mastery = 833,
              versatility = 92,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
        },
        ["MONK"] = {
          ["brewmaster"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/brewmaster/monk/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1136,
              haste = 289,
              mastery = 395,
              versatility = 658,
            },
            order = { "crit", "versatility", "mastery", "haste" },
          },
          ["mistweaver"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/mistweaver/monk/raid/overview/mythic/all-bosses",
            targets = {
              crit = 912,
              haste = 1184,
              mastery = 195,
              versatility = 172,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["windwalker"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/windwalker/monk/raid/overview/mythic/all-bosses",
            targets = {
              crit = 818,
              haste = 907,
              mastery = 649,
              versatility = 154,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
        ["PALADIN"] = {
          ["holy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/holy/paladin/raid/overview/mythic/all-bosses",
            targets = {
              crit = 446,
              haste = 827,
              mastery = 1070,
              versatility = 143,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["protection"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/protection/paladin/raid/overview/mythic/all-bosses",
            targets = {
              crit = 685,
              haste = 1030,
              mastery = 429,
              versatility = 257,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["retribution"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/retribution/paladin/raid/overview/mythic/all-bosses",
            targets = {
              crit = 830,
              haste = 620,
              mastery = 946,
              versatility = 76,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["PRIEST"] = {
          ["discipline"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/discipline/priest/raid/overview/mythic/all-bosses",
            targets = {
              crit = 835,
              haste = 1028,
              mastery = 478,
              versatility = 112,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
          ["holy"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/holy/priest/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1049,
              haste = 548,
              mastery = 620,
              versatility = 207,
            },
            order = { "crit", "mastery", "haste", "versatility" },
          },
          ["shadow"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/shadow/priest/raid/overview/mythic/all-bosses",
            targets = {
              crit = 491,
              haste = 972,
              mastery = 973,
              versatility = 82,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
        },
        ["ROGUE"] = {
          ["assassination"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/assassination/rogue/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1169,
              haste = 647,
              mastery = 508,
              versatility = 105,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["outlaw"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/outlaw/rogue/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1154,
              haste = 857,
              mastery = 285,
              versatility = 171,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["subtlety"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/subtlety/rogue/raid/overview/mythic/all-bosses",
            targets = {
              crit = 760,
              haste = 670,
              mastery = 929,
              versatility = 92,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
        },
        ["SHAMAN"] = {
          ["elemental"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/elemental/shaman/raid/overview/mythic/all-bosses",
            targets = {
              crit = 819,
              haste = 484,
              mastery = 1076,
              versatility = 92,
            },
            order = { "mastery", "crit", "haste", "versatility" },
          },
          ["enhancement"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/enhancement/shaman/raid/overview/mythic/all-bosses",
            targets = {
              crit = 285,
              haste = 933,
              mastery = 1171,
              versatility = 84,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["restoration"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/restoration/shaman/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1166,
              haste = 452,
              mastery = 337,
              versatility = 396,
            },
            order = { "crit", "haste", "versatility", "mastery" },
          },
        },
        ["WARLOCK"] = {
          ["affliction"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/affliction/warlock/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1023,
              haste = 867,
              mastery = 500,
              versatility = 107,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["demonology"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/demonology/warlock/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1116,
              haste = 801,
              mastery = 459,
              versatility = 96,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["destruction"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/destruction/warlock/raid/overview/mythic/all-bosses",
            targets = {
              crit = 979,
              haste = 834,
              mastery = 558,
              versatility = 95,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
        },
        ["WARRIOR"] = {
          ["arms"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/arms/warrior/raid/overview/mythic/all-bosses",
            targets = {
              crit = 1097,
              haste = 945,
              mastery = 348,
              versatility = 71,
            },
            order = { "crit", "haste", "mastery", "versatility" },
          },
          ["fury"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/fury/warrior/raid/overview/mythic/all-bosses",
            targets = {
              crit = 477,
              haste = 1046,
              mastery = 1047,
              versatility = 88,
            },
            order = { "mastery", "haste", "crit", "versatility" },
          },
          ["protection"] = {
            sourceUrl = "https://www.archon.gg/wow/builds/protection/warrior/raid/overview/mythic/all-bosses",
            targets = {
              crit = 666,
              haste = 1104,
              mastery = 431,
              versatility = 216,
            },
            order = { "haste", "crit", "mastery", "versatility" },
          },
        },
      },
    },
  },
}
